platform :ios,'8.0'

pod 'MJExtension'
pod 'SDAutoLayout'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'FMDB'
pod 'MBProgressHUD'
pod 'MWPhotoBrowser'
pod 'CTAssetsPickerController'
pod 'ZFPlayer'
pod 'EAIntroView'